[tool.poetry]
name = "game"
version = "0.1.0"
description = ""
authors = ["Horrorzero <YOUR_EMAIL>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pygame = "^2.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
